# -*- coding: utf-8 -*-
"""CP-DYNAMIC-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12i7ETjFvJ8SjbWOae7spZnNbUYFRhGjz
"""

from google.colab import drive
drive.mount('/content/drive')

# =========================
# IMPORTS
# =========================

import pandas as pd
from collections import deque
import matplotlib.pyplot as plt

# =========================
# CARREGAMENTO DOS DADOS (RM FINAL ÍMPAR)
# =========================

df = pd.read_csv('/content/drive/MyDrive/FIAP/SEGUNDO ANO/DYNAMIC/Check_point_1_dados_logistica_RA_final impar.csv')

# =========================
# CLASSIFICAÇÃO DE VALOR (lambda)
# =========================

df["faixa_valor"] = df["valor_frete"].apply(
    lambda x: "alto" if x >= 1600 else "medio" if x >= 1200 else "baixo"
)

# =========================
# SCORE BASE (VETORIZADO)
# =========================
# Complexidade: O(n)

df["valor_prioridade"] = 0

df["valor_prioridade"] += df["prioridade_cliente"].map({
    "vip": 3
}).fillna(1)

df["valor_prioridade"] += df["situacao_rota"].map({
    "critica": 3,
    "atencao": 2
}).fillna(1)

df["valor_prioridade"] += df["faixa_valor"].map({
    "alto": 2,
    "medio": 1
}).fillna(0)

# =========================
# INTERAÇÕES (REGRAS DE NEGÓCIO)
# =========================

df["valor_prioridade"] += (
    (df["situacao_rota"] == "critica") &
    (df["prazo_dias"] <= 3)
) * 3

df["valor_prioridade"] += (
    (df["prioridade_cliente"] == "vip") &
    (df["faixa_valor"] == "alto")
) * 2

df["valor_prioridade"] += (
    (df["situacao_rota"] == "critica") &
    (df["prioridade_cliente"] == "vip")
) * 2

df["valor_prioridade"] += (df["prazo_dias"] <= 2) * 2

# =========================
# NORMALIZAÇÃO
# =========================

df["valor_prioridade"] = df["valor_prioridade"].clip(3, 12)

# =========================
# CLASSIFICAÇÃO FINAL
# =========================

def classificar_prioridade(p):
    if p >= 8:
        return "alta"
    elif p >= 5:
        return "media"
    else:
        return "baixa"

df["categoria_prioridade"] = df["valor_prioridade"].apply(classificar_prioridade)

# =========================
# ORDENAÇÃO
# =========================
# Complexidade: O(n log n)

df = df.sort_values(by="valor_prioridade", ascending=False)

# =========================
# OUTPUT FINAL
# =========================

print("\nTabela final:")
display(df)

# =========================
# RECURSÃO SIMPLES
# =========================

def processar_entregas_recursivo(lista, index=0):
  """
  Recursão aplicada para percorrer a lista de entregas e gerar uma nova estrutura
  Simula processamento sequencial de cargas
  Complexidade: O(n)
  """
  if index >= len(lista):
      return []

  entrega = lista[index]
  prioridade = entrega["valor_prioridade"]

  resultado = {
      "id": entrega["entrega_id"],
      "prioridade": prioridade,
      "categoria": classificar_prioridade(prioridade)
  }

  return [resultado] + processar_entregas_recursivo(lista, index + 1)

lista_dict = df.to_dict(orient="records")
resultado_recursivo = processar_entregas_recursivo(lista_dict)

print("\nProcessamento recursivo:")
print(resultado_recursivo[:5])

# =========================
# LISTA
# =========================

lista_ids = df["entrega_id"].tolist()

# =========================
# DEQUE
# =========================

fila = deque(lista_ids)
print("\nFila de entregas (deque):")
print(fila)
while fila:
    entrega = fila.popleft()
    print(f"Processando entrega {entrega}")

# =========================
# DICIONÁRIO + TUPLA
# =========================

mapa = {
    row["entrega_id"]: (row["origem"], row["destino"])
    for _, row in df.iterrows()
}

print("\nMapa de cargas (dict + tuple):")
print(mapa)

# =========================
# ANÁLISE DE COMPLEXIDADE
# =========================

# 1. Classificação com apply/map
# Complexidade: O(n)

# 2. Interações (operações vetorizadas)
# Complexidade: O(n)

# 3. Ordenação
# Complexidade: O(n log n)

# 4. Recursão (processamento de entregas)
# Complexidade: O(n)

# 5. Criação de estruturas (lista, dict, deque)
# Complexidade: O(n)

# =========================
# CONTAGEM
# =========================

contagem = df["categoria_prioridade"].value_counts()

# =========================
# GRÁFICO
# =========================

plt.figure()
contagem.plot(kind="bar")
plt.xlabel("Nível de Prioridade")
plt.ylabel("Quantidade")
plt.title("Distribuição de Prioridades")
plt.show()